name: Get Pzubslic IP

on:
  push:
    branches:
      - main

jobs:
  set-env:
    name: set-env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: get SDK
        run: pip install huaweicloudsdkvpc
      - name: Get Public IP
        id: public-ip
        run:  echo "ip_address=$(dig +short myip.opendns.com @resolver1.opendns.com)\n" >> $GITHUB_OUTPUT
        
        
      - name: Run Python Script
        id: first_id
        run: |
          sudo python script.py
        env:
          CLOUD_SDK_AK: ${{ secrets.CLOUD_SDK_AK }}
          CLOUD_SDK_SK: ${{ secrets.CLOUD_SDK_SK }}

          
      #- name: Run Python Script2
      #  run: python script2.py
      #  env:
      #    CLOUD_SDK_AK: ${{ secrets.CLOUD_SDK_AK }}
      #    CLOUD_SDK_SK: ${{ secrets.CLOUD_SDK_SK }}
      #    SG_RULE_ID:  ${{ steps.first_id.outputs.sg_rule_id }}
